### ISSUE TITLE
mobile doesn't support scroll on fixed menu

### ISSUE THREAD

**Issue by octavioamu** [geedmo/yamm#4]
Doesn't support scroll if the content doesn't fit the heigh of the screen hiding part of it
A solution could be just add :
```
.yamm .collapse, .yamm .dropup, .yamm .dropdown {
    overflow: auto;
    max-height: 100vh;
}

```

![image](https://user-images.githubusercontent.com/1358093/73497713-36b3d080-439a-11ea-825e-b43327acd7c0.png)

**Comment by geedmo** [comment]
Hi, thanks for your contribution.
I think your approach is totally fine and I'd like to implement it using a separated class (e.g. yamm-scrollable) to avoid mixin styles with bootstrap default like .collapse.

Just one question, is there any reason why you target .dropdown/up too?

**Comment by JamesShaver** [comment]
Thanks @octavioamu, this solved my issue. @geedmo, I'd like to see how you would implement this in a separated class.

**Comment by geedmo** [comment]
@JamesShaver like this
```
.yamm-scrollable {
    overflow: auto;
    max-height: 100vh;
}
```
Then add this class to anything you want (collapse, dropdown, etc).
Anyway, I'm considering not to include this changes because the height to be used feels like an opinionated value.

A css like this for example
```
.yamm-scrollable {
    overflow: auto;
    max-height: calc(100vh - 40px - 20px);
}
```
will substract to the screen height, the height the header and an extra for bottom space. Also, it works better in my opinion applied to the .navbar-nav (than .collapse)
